[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"] 
****
The goal of this project is to create Viade, which is a decentralized routes management system based on the Solid specifications.

Along this documentation, you will be able to find the prominent requirements of our project, quality goals for the software architecture and stakeholders with their specific interests.

****

=== Requirements Overview

[role="arc42help"]
****
[options="header",cols="1,2"]
|===
|Requirement|Description
| Decentralized architecture | The application will be separated from the data storage, that means all the data including messages.
|Routes | User can view their routes in their own PODs. 
|Maps | User can view the routes stored on a map.
|Shared files |  Pictures, videos or information about a route can be shared with other friends.
|Notifications | When some friend of our user shares a route with him, he can get notifications.
|Group users| Users can have groups of friends with whom they may want to share a route. 
|Interoperability| It should be possible to view routes loaded by users that are using a different app.
|===

It is important to be considered that our application could work on a mobile devices and user can share their routes while they are doing the routes.
****

=== Quality Goals

[role="arc42help"]
****

.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]

