[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
.Conventions
|===
|Constraint|Explanation
|Code | We must use React 
| Language | Documentation and code is developed in English
| Documentation | All our documentation is based on the arc42 template 
|===

.Organizational Constraints
|===
|Constraint|Explanation
|Members of our team| Carlos Menéndez, Andrés Ángel González, Andrea López, Christian Gabriel, Elena Díaz, Iván Rodríguez, María González
|Project duration |The time we are given to develop our project are around 4 months
|Participation control | The team has a git repository with the complete commit history of all the members to take track of the participation
|Minutes| In the practical classes we write all the progress or modifications done in the project
|===