[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following seection.
****

=== Quality Scenarios

[role="arc42help"]
.Table 1. Disponibility

.Table 2. Security
.Table 3. Performance
.Table 4. Testability
.Table 5. Usability
|===
|Scenario|Explanation|Priority
| Easy to learn | The users get used easily to the application|Medium
|Good-looking interface |If the app colours are attracting for the user it will be easier and comfortable to use it|Low
|===
.Table 6. Maintenance
.Table 7. Portability
.Table 8. Interoperability

