[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree

[role="arc42help"]
The following diagram represents the quality scenarios which tries to show some of this project´s quality attributes, sorted by priority from high priority to lower priority.

****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following seection.
****

=== Quality Scenarios

[role="arc42help"]

.Security
|===
|Scenario|Explanation|Priority
|Decentralized data|If the server hosting the app falls, data remains safe|High
|Data Storage|From the user´s personal computer to a Solid server|
|Login control| Each user has access only to its own account and data|High
|Private routes| Every user's routes are private so if one user wants to share one route with a friend he has to give permissions|High
|===

.Usability
|===
|Scenario|Explanation|Priority
| Easy to learn | The users get used easily to the application|Medium
|Good-looking interface |If the app colours are attracting for the user it will be easier and comfortable to use it|Low
|Accesibility|Mouse is not required to use the app|Low
|===

.Modifiability
|===
|Scenario|Explanation|Priority
| Clear and coherent purpose | Developers can find in the documentation where to work|Medium
|Established methology |Visible in the documentation|Medium
|===

.Disponibility
.Performance
|===
|Scenario |Explanation|Priority
| Interactions with the UI are shown fast|Every change or interaction the user makes will appear without making him wait a long time | Medium
|===
.Testability
.Maintenance
.Portability
.Interoperability
