ignore:
  - "src/index.js"
  - "src/serviceWorker.js"
  - "src/MainPage/Panel/Map/Map.js"
  - "src/MainPage/Panel/CreateRoute/CreateRoute.js"
  - "src/MainPage/Panel/CreateRoute/CreateRoutePanel.js"
  - "src/MainPage/Panel/ShareRoute/ShareRoute.js"
  - "src/MainPage/Main-page.js"
  - "src/MainPage/Panel/CreateRoute/UploadRouteToPod.js"
  - "src/MainPage/Panel/Friends/Friends.js"
  - "src/MainPage/Panel/SharedRoutes/SharedRoutes.js"
  - "src/MainPage/Panel/Notifications/Notifications.js"
  - "src/MainPage/Panel/AddRoute/AddRoute.js"
